FROM madnificent/ember:5.12.0 AS builder

LABEL maintainer="info@redpencil.io"

WORKDIR /app
COPY package.json .
RUN npm install

COPY . .
RUN ember build --environment production
RUN cd dist && npm install

FROM redpencil/fastboot-app-server:1.3.0

COPY --from=builder /app/dist /app

ENV EMBER_VO_HEADER_WIDGET_URL=""
ENV EMBER_VO_FOOTER_WIDGET_URL=""
