FROM madnificent/ember:4.3.0 AS builder

LABEL maintainer="info@redpencil.io"

WORKDIR /app
COPY package.json .
RUN npm install

COPY . .
RUN ember build --environment production

FROM redpencil/fastboot-app-server:1.1.0

COPY --from=builder /app/dist /app

ENV EMBER_VO_HEADER_WIDGET_URL=""
ENV EMBER_VO_FOOTER_WIDGET_URL=""
